In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torch.utils.data import Dataset  

In [3]:
softmax_output = torch.tensor([
    [0.0310, 0.0419, 0.0284, 0.0549, 0.0342, 0.0430, 0.0340, 0.0345, 0.0514,
     0.0405, 0.0310, 0.0464, 0.0306, 0.0473, 0.0189, 0.0424, 0.0261, 0.0245,
     0.0389, 0.0274, 0.0265, 0.0455, 0.0240, 0.0516, 0.0292, 0.0372, 0.0306,
     0.0281],
    [0.0246, 0.0444, 0.0270, 0.0592, 0.0310, 0.0465, 0.0345, 0.0310, 0.0578,
     0.0407, 0.0301, 0.0452, 0.0290, 0.0552, 0.0183, 0.0449, 0.0301, 0.0219,
     0.0386, 0.0224, 0.0256, 0.0456, 0.0212, 0.0489, 0.0249, 0.0359, 0.0332,
     0.0324]
])
softmax_output.sum(dim=1)

tensor([1.0000, 1.0001])

In [32]:
def infer(probs, threshold):
    # TODO: implement this
    # top1 = p1 top 2 = p2
    # if p2 > p1 * 0.8, class include both p1 and p2, else p1 only
    top_values, top_indices = probs.topk(probs.shape[0])
    print(top_values)
    print(top_indices)
    selected = top_indices[0:1]
    for i in range(1, probs.shape[0]):
        pre_value = top_values[i-1].item()
        value = top_values[i].item()
        index = top_indices[i:i+1]
        print(pre_value, value, index)
        if value > threshold * pre_value:
            selected = torch.cat((selected, index), dim=0)
        else:
            return selected
    return selected
    

In [33]:
result = infer(softmax_output[0], 0.8)

tensor([0.0549, 0.0516, 0.0514, 0.0473, 0.0464, 0.0455, 0.0430, 0.0424, 0.0419,
        0.0405, 0.0389, 0.0372, 0.0345, 0.0342, 0.0340, 0.0310, 0.0310, 0.0306,
        0.0306, 0.0292, 0.0284, 0.0281, 0.0274, 0.0265, 0.0261, 0.0245, 0.0240,
        0.0189])
tensor([ 3, 23,  8, 13, 11, 21,  5, 15,  1,  9, 18, 25,  7,  4,  6,  0, 10, 12,
        26, 24,  2, 27, 19, 20, 16, 17, 22, 14])
0.05490000173449516 0.051600001752376556 tensor([23])
0.051600001752376556 0.05139999836683273 tensor([8])
0.05139999836683273 0.04729999974370003 tensor([13])
0.04729999974370003 0.04639999940991402 tensor([11])
0.04639999940991402 0.045499999076128006 tensor([21])
0.045499999076128006 0.0430000014603138 tensor([5])
0.0430000014603138 0.042399998754262924 tensor([15])
0.042399998754262924 0.04190000146627426 tensor([1])
0.04190000146627426 0.04050000011920929 tensor([9])
0.04050000011920929 0.03889999911189079 tensor([18])
0.03889999911189079 0.03720000013709068 tensor([25])
0.03720000013709068 0.034499999

In [85]:
infer(softmax_output[0], 0.85)

tensor([0.0549, 0.0516, 0.0514, 0.0473, 0.0464, 0.0455, 0.0430, 0.0424, 0.0419,
        0.0405, 0.0389, 0.0372, 0.0345, 0.0342, 0.0340, 0.0310, 0.0310, 0.0306,
        0.0306, 0.0292, 0.0284, 0.0281, 0.0274, 0.0265, 0.0261, 0.0245, 0.0240,
        0.0189])
tensor([ 3, 23,  8, 13, 11, 21,  5, 15,  1,  9, 18, 25,  7,  4,  6,  0, 10, 12,
        26, 24,  2, 27, 19, 20, 16, 17, 22, 14])
0.05490000173449516 0.051600001752376556 tensor([23])
0.051600001752376556 0.05139999836683273 tensor([8])
0.05139999836683273 0.04729999974370003 tensor([13])
0.04729999974370003 0.04639999940991402 tensor([11])
0.04639999940991402 0.045499999076128006 tensor([21])
0.045499999076128006 0.0430000014603138 tensor([5])
0.0430000014603138 0.042399998754262924 tensor([15])
0.042399998754262924 0.04190000146627426 tensor([1])
0.04190000146627426 0.04050000011920929 tensor([9])
0.04050000011920929 0.03889999911189079 tensor([18])
0.03889999911189079 0.03720000013709068 tensor([25])
0.03720000013709068 0.034499999

tensor([ 3, 23,  8, 13, 11, 21,  5, 15,  1,  9, 18, 25,  7,  4,  6,  0, 10, 12,
        26, 24,  2, 27, 19, 20, 16, 17, 22])

In [87]:
infer(softmax_output[0], 0.9)

tensor([0.0549, 0.0516, 0.0514, 0.0473, 0.0464, 0.0455, 0.0430, 0.0424, 0.0419,
        0.0405, 0.0389, 0.0372, 0.0345, 0.0342, 0.0340, 0.0310, 0.0310, 0.0306,
        0.0306, 0.0292, 0.0284, 0.0281, 0.0274, 0.0265, 0.0261, 0.0245, 0.0240,
        0.0189])
tensor([ 3, 23,  8, 13, 11, 21,  5, 15,  1,  9, 18, 25,  7,  4,  6,  0, 10, 12,
        26, 24,  2, 27, 19, 20, 16, 17, 22, 14])
0.05490000173449516 0.051600001752376556 tensor([23])
0.051600001752376556 0.05139999836683273 tensor([8])
0.05139999836683273 0.04729999974370003 tensor([13])
0.04729999974370003 0.04639999940991402 tensor([11])
0.04639999940991402 0.045499999076128006 tensor([21])
0.045499999076128006 0.0430000014603138 tensor([5])
0.0430000014603138 0.042399998754262924 tensor([15])
0.042399998754262924 0.04190000146627426 tensor([1])
0.04190000146627426 0.04050000011920929 tensor([9])
0.04050000011920929 0.03889999911189079 tensor([18])
0.03889999911189079 0.03720000013709068 tensor([25])
0.03720000013709068 0.034499999

tensor([ 3, 23,  8, 13, 11, 21,  5, 15,  1,  9, 18, 25,  7,  4,  6,  0, 10, 12,
        26, 24,  2, 27, 19, 20, 16, 17, 22])

In [86]:
infer(softmax_output[0], 0.95)

tensor([0.0549, 0.0516, 0.0514, 0.0473, 0.0464, 0.0455, 0.0430, 0.0424, 0.0419,
        0.0405, 0.0389, 0.0372, 0.0345, 0.0342, 0.0340, 0.0310, 0.0310, 0.0306,
        0.0306, 0.0292, 0.0284, 0.0281, 0.0274, 0.0265, 0.0261, 0.0245, 0.0240,
        0.0189])
tensor([ 3, 23,  8, 13, 11, 21,  5, 15,  1,  9, 18, 25,  7,  4,  6,  0, 10, 12,
        26, 24,  2, 27, 19, 20, 16, 17, 22, 14])
0.05490000173449516 0.051600001752376556 tensor([23])


tensor([3])

In [36]:
softmax_output[0].shape

torch.Size([28])

In [ ]:
result.shape

torch.Size([27])

In [76]:
def calculate_acc(predicted, labels):
    concat = torch.cat((predicted, labels), dim=0)
    unique = torch.unique(concat)
    matches = torch.eq(predicted[:, None], labels)
    correct = matches.sum()
    return (correct / unique.shape[0]).item()

In [80]:
test_pred1 = torch.tensor([19, 21])
test_label1 = torch.tensor([21])
test_label2 = torch.tensor([21, 23])
test_label3 = torch.tensor([210, 230])

In [81]:
calculate_acc(test_pred1, test_label1)

0.5

In [82]:
calculate_acc(test_pred1, test_label2)

0.3333333432674408

In [ ]:
calculate_acc(test_pred1, test_label3)

0.0